import CPrinterDriver
import Foundation

/// One submitted job: an event stream, a queryable state and a terminal result that
/// survives an app restart.
///
/// The ABI maps one underlying job to one stable handle, so re-submitting an idempotency
/// key returns the identical object — `===` is a meaningful test for "this is the same
/// job, not a second print".
///
/// ### Threading
///
/// Every property here is safe to read from any thread. ``events``, the closures passed to
/// ``observe(onProgress:completion:)`` and the resumption of ``result`` are all delivered
/// on the driver's private serial queue, in that queue's order — so an `AsyncStream` and a
/// progress closure attached to the same job see the same sequence, and the terminal
/// notification always comes after the last event.
public final class PrintJob: @unchecked Sendable {
  private let core: DriverCore
  private let handle: OpaquePointer
  private let hub: JobEventHub
  private let trampoline: JobEventTrampoline
  private let awaiter: JobResultAwaiter
  private let lock = NSLock()
  private var isSubscribed = false

  /// The core's own job id.
  public let id: String

  /// The idempotency key this job is filed under, generated by the core when the caller
  /// did not supply one.
  public let key: String

  /// Which ordered fence was available to prove this job finished. See
  /// ``Printer/completionMechanism``.
  ///
  /// This is the printer's capability, not a claim about this job. What the job itself
  /// actually earned is in ``JobResult/done(confidence:grade:authority:method:)``.
  public let completionMechanism: CompletionMechanism

  init(core: DriverCore, handle: OpaquePointer, mechanism: CompletionMechanism) {
    self.core = core
    self.handle = handle
    completionMechanism = mechanism
    id = String(cString: pd_job_id(handle))
    key = String(cString: pd_job_key(handle))
    hub = JobEventHub(delivery: core.delivery)
    trampoline = JobEventTrampoline(hub: hub, delivery: core.delivery)
    awaiter = JobResultAwaiter(core: core, handle: handle)
    core.retain(trampoline: trampoline)
  }

  /// The receipt verification identifier this attempt printed under — the four
  /// characters the ticket carries as `V:` (docs/api.md §14).
  ///
  /// `nil` until the job reaches a worker, and `nil` for good on a printer whose fence
  /// is not `GS ( H`: the identifier *is* the wire token, so a printer that has no wire
  /// token has none to print. Look one up with ``PrinterDriver/job(token:)``.
  public var printToken: String? {
    let value = String(cString: pd_job_print_token(handle))
    return value.isEmpty ? nil : value
  }

  /// The identifier the job's cut fence carried. Same lifetime rules as
  /// ``printToken``; it resolves through ``PrinterDriver/job(token:)`` too.
  public var cutToken: String? {
    let value = String(cString: pd_job_cut_token(handle))
    return value.isEmpty ? nil : value
  }

  // MARK: - Current state

  /// How many times this key has been printed. 1 for an original, 2 and up for reprints.
  public var attempt: UInt32 { pd_job_attempt(handle) }

  /// Where the job is right now.
  public var state: JobState { JobState(bridging: pd_job_current_state(handle).rawValue) }

  /// What evidence backs the current claim.
  public var confidence: ConfidenceLevel {
    ConfidenceLevel(bridging: pd_job_confidence(handle).rawValue)
  }

  /// Whether the job has reached a terminal state. A terminal job never emits again.
  public var isTerminal: Bool { pd_job_is_terminal(handle) != 0 }

  // MARK: - Feedback

  /// Every step of the job, ending with its terminal event.
  ///
  /// Each access returns an independent stream that replays what has happened so far and
  /// then follows the live ones, so attaching late loses nothing. The stream finishes
  /// after the terminal event — it is a completion signal, not a result: read ``result``
  /// for the tri-state answer.
  public var events: AsyncStream<JobEvent> {
    subscribeIfNeeded()
    return hub.makeStream()
  }

  /// The terminal result, awaited.
  ///
  /// Safe to await from any number of tasks and at any time, including long after the job
  /// finished: the answer is computed once and cached.
  public var result: JobResult {
    get async {
      subscribeIfNeeded()
      return await withCheckedContinuation { continuation in
        awaiter.whenSettled { continuation.resume(returning: $0) }
      }
    }
  }

  /// Watches the job with closures instead of `async` — see
  /// ``Printer/print(_:options:onProgress:completion:)``.
  ///
  /// - Parameters:
  ///   - onProgress: called for every ``JobEvent`` in order, starting with the ones
  ///     already recorded.
  ///   - completion: called **exactly once**, after the last `onProgress` call, with the
  ///     tri-state result. Calling this method again adds another pair of observers; each
  ///     `completion` still fires exactly once.
  public func observe(
    onProgress: @escaping (JobEvent) -> Void = { _ in },
    completion: @escaping (JobResult) -> Void
  ) {
    subscribeIfNeeded()
    hub.addProgressHandler(onProgress)
    awaiter.whenSettled(completion)
  }

  // MARK: - Internals

  /// Attaches to the ABI once, on first use.
  ///
  /// `pd_subscribe_job` replays the recorded history on the calling thread and then
  /// streams the rest from the printer's worker, so subscribing twice would double every
  /// event — there is no unsubscribe to undo it with.
  private func subscribeIfNeeded() {
    lock.lock()
    let isFirst = !isSubscribed
    isSubscribed = true
    lock.unlock()
    guard isFirst else { return }

    // The window matters: the callback goes live before the replay runs. See
    // JobEventTrampoline for why that would otherwise reorder a job's first events.
    trampoline.beginSubscription()
    pd_subscribe_job(
      core.handle, handle, jobEventThunk, Unmanaged.passUnretained(trampoline).toOpaque())
    trampoline.endSubscription()
    // Closing the stream is driven by the same settlement that produces the result, which
    // the core publishes only after the terminal event has gone out to subscribers. The
    // stream therefore always carries its last event before it finishes.
    awaiter.whenSettled { [hub] _ in hub.finish() }
  }
}
